### ISSUE TITLE
Search filtering seems not working

### ISSUE THREAD

**Issue by ghost** [mafiascum/privatetopics#2]
Search filtering seems not working - content of private topic is visible for unauthorized user on the search results page.

Tested on: MySQL 5.7, php 7.1, Windows 10, phpBB 3.2.

**Comment by mmason930** [comment]
Thanks! Are you a member of MafiaScum? If so, could you send me(Kison) a PM? Thanks!

**Comment by cciccia** [comment]
I suspect you are using native search rather than mysql.

**Comment by ghost** [comment]
@mmason930 No, I'm here from Google.
@cciccia You are right, there are no problems on MySQL search backend.

**Comment by cciccia** [comment]
won't fix; only supporting sphinx
